### ISSUE TITLE
Modify block sidebar UX

### ISSUE THREAD

**Issue by daniela0321** [Flare-Hub/image-map-connect-plugin#131]
--------------

- [x] Use default WordPress Icons and place them as follows
  - Order: Desktop, Tablet, Mobile
  - Size: 15px
--------------

- [x] Use more accordions to group the settings, see e.g. example below

![Image](https://github.com/Flare-Hub/image-map-connect-plugin/assets/80820520/164da40c-a520-4c3c-a81a-593c8bf5172a)

--------------

- [x] Rename titles as follows:

- _Default_ Image Frame
- Marker Query
- Popup / Size and Spacing
- Popup / Onset
- Popup / Featured Image
- Popup / Title
- Popup / Metadata
- Popup / Excerpt

--------------

- [x] Should the default open one be responsive settings instead of Marker Query? In this way users don't miss it by accident?

--------------

- [x] Make text after the plugin name shorter, e.g. : "Display interactive images"

![Image](https://github.com/Flare-Hub/image-map-connect-plugin/assets/80820520/83e68e48-00f5-47df-bd1d-7beb72c38ece)

--------------

**Comment by dutchigor** [comment]
Agreed to leave the Marker Query open as the default panel but move it to the top.
