### ISSUE TITLE
Creating a Search Field

### ISSUE THREAD

**Issue by ruselshark** [Flare-Hub/image-map-connect-plugin#148]
Please add a search field for objects on the map

**Comment by dutchigor** [comment]
Image Map Connect is designed to be used inside the standard WorkdPress Query Loop block. This block is responsible for filtering the list of posts to show.

This means that any search block that works with the Query Loop block can be used to filter the image map. Note that most search plugins affect the main query in which case you need to make sure that your Query Loop block inherits the query from the template. If your Query Loop block does not inherit the template, look for a block that can modify the query of the Query Loop block itself.

I hope this answers your question. If not, feel free to reopen the issue.
